updated the pipeline

diff --git a/.github/workflows/docker_image.yml b/.github/workflows/docker_image.yml
--- a/.github/workflows/docker_image.yml
+++ b/.github/workflows/docker_image.yml
@@ -21,14 +21,14 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: lint
-        uses: hadolint/hadolint-action@v3.1.0
-        with:
-            dockerfile: Dockerfile
-            no-color : false
-            no-fail: true
-            ignored:
-                DL3018
+    #   - name: lint
+    #     uses: hadolint/hadolint-action@v3.1.0
+    #     with:
+    #         dockerfile: Dockerfile
+    #         no-color : false
+    #         no-fail: true
+    #         ignored: DL3018
+                
                  
       - name: Docker metadata
         id: metadata
@@ -49,19 +49,19 @@ jobs:
     #       ignore-unchanged: true
     #       only-severities: critical,high
 
-      - name: Check vulnerability scan result
-        run: |
-          if [[ "${{ steps.vulnerability_scan.outcome }}" == "success" ]]; then
-            echo "Vulnerability scan passed. Proceeding to build and push Docker image."
-          else
-            echo "Vulnerability scan failed. Skipping Docker image build and push."
-            exit 1
-          fi
+    #   - name: Check vulnerability scan result
+    #     run: |
+    #       if [[ "${{ steps.vulnerability_scan.outcome }}" == "success" ]]; then
+    #         echo "Vulnerability scan passed. Proceeding to build and push Docker image."
+    #       else
+    #         echo "Vulnerability scan failed. Skipping Docker image build and push."
+    #         exit 1
+    #       fi
 
-      - name: Build and push Docker image
-        if: success()  # Only run if vulnerability scan succeeded
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          push: true
-          tags: ${{ steps.metadata.outputs.tags }}
+    #   - name: Build and push Docker image
+    #     if: success()  # Only run if vulnerability scan succeeded
+    #     uses: docker/build-push-action@v5
+    #     with:
+    #       context: .
+    #       push: true
+    #       tags: ${{ steps.metadata.outputs.tags }}
